import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import AppBar from '../AppBar'
import ListItem from '@mui/material/ListItem';
import Box from '@mui/material/Box';
import List from './List'
import Typography from '@mui/material/Typography';
import TwitterIcon from '@mui/icons-material/Twitter';
import IconButton from '@mui/material/IconButton';
import TelegramIcon from '@mui/icons-material/Telegram';
import RedditIcon from '@mui/icons-material/Reddit';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ErgoNation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppBar isHome={false}/>
        <Box sx={{display:{ xs: 'none', md: 'flex' }}}>
          <h2 className={styles.title}>
            Unique <a>Identities</a>
          </h2>
        </Box>
        <Box sx={{display:{ xs: 'flex', md: 'none' }}}>
          <h3 className={styles.titleSmall}>
            Proof of <a>Humanity</a>
          </h3>
        </Box>
        <p className={styles.description}>
          Join Ergo Nation by participating in our next event{' '}
        </p>
        <Box> 
          <List/>
        </Box>
      </main>

      <footer className={styles.footer}>
       <IconButton
              size="large"
              aria-label="account of current user"
              aria-controls="menu-appbar"
              aria-haspopup="true"
              color="inherit"
            >
          <TwitterIcon/>
        </IconButton>
         <IconButton
              size="large"
              aria-label="account of current user"
              aria-controls="menu-appbar"
              aria-haspopup="true"
              color="inherit"
            >
          <TelegramIcon/>
        </IconButton>
        <IconButton
              size="large"
              aria-label="account of current user"
              aria-controls="menu-appbar"
              aria-haspopup="true"
              color="inherit"
            >
            <RedditIcon/>
          </IconButton>
        <IconButton
              size="large"
              aria-label="account of current user"
              aria-controls="menu-appbar"
              aria-haspopup="true"
              color="inherit"
            >
            <Image src="/Discord-Logo-Black.svg" alt="Discord Logo" width={24} height={24} />
          </IconButton>
      </footer>
    </div>
  )
}
