import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from './ResponsiveAppBar.tsx'
import ListItem from '@mui/material/ListItem';



export default function Home() {
  return (
    <div className={styles.container}>
    <ResponsiveAppBar/>
      <Head>
        <title>ErgoNation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <span className={styles.ergonnationlogo}>
            <Image src="/ergonation.svg" alt="Ergonation Logo" width={1000} height={500}/>
          </span>
        <h1 className={styles.title}>
          Proof of <a href="https://nextjs.org">Human!</a>
        </h1>

        <p className={styles.description}>
          Get started by joining our next event{' '}
        </p>

        <div className={styles.numberlist}>
          <h3>Create ID</h3>
            <div className ={styles.listItems}>
              <ListItem sx={{ display: 'list-item' }}>
                Create a new <a href="https://ergoplatform.org/en/blog/2022-03-10-storing-crypto-on-ergo-nautilus-wallet/"> Ergo wallet</a> address. This address is your anonymous ID. Do not reveal it to anyone.
              </ListItem>
              <ListItem sx={{ display: 'list-item' }}>
                Use <a href="https://github.com/ergoMixer/ergoMixBack/releases">ErgoMixer</a> to send a minimum of 1 ERG into it. The mixing process may take some time. Start it right away to be ready for the verification event.
              </ListItem>
              <ListItem sx={{ display: 'list-item' }}>
                All funds going in and out of the ID address must go through the mixer to preserve anonymity.            
              </ListItem>
            </div>
          <h3>Verify ID </h3>
            <div className ={styles.listItems}>
              <ListItem sx={{ display: 'list-item' }}>
                Join the first monthly ID verification event on 7.6.2022 at 20.00 UTC for instructions. The event itself will start 20.15 UTC, and end 20.30 UTC.
              </ListItem>
              <ListItem sx={{ display: 'list-item' }}>
                Participants will play a short game. If successful, they will be able to verify the ID on-chain.
              </ListItem>
            </div>
          <h3>Use ID </h3>
            <div className ={styles.listItems}>
              <ListItem sx={{ display: 'list-item' }}>
                Ergo projects can engage the ID holders in governance, testing, whitelist, rewards, tasks, etc.
              </ListItem>
              <ListItem sx={{ display: 'list-item' }}>
                The IDs will gather reputation through actions in the ecosystem. We encourage projects to engage those IDs that actively support decentralization, anonymity and the spirit of Ergo (see Ergo Manifesto).
              </ListItem>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          <code className={styles.code}>pages/index.js</code>
        </a>
      </footer>
    </div>
  )
}
