import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AppBar from './AppBar'
import ListItem from '@mui/material/ListItem';
import Box from '@mui/material/Box';
import Link from 'next/link'
import Footer from './Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ErgoNation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppBar isHome = {true}/>
        <div className={styles.ergonationlogo}>
          <Image src="/ergonation.svg" className ={styles.filtergreen} alt="Ergonation Logo" width={1000} height={400}/>
        </div>
        <Box sx={{display:{ xs: 'none', md: 'flex' }}}>
          <h2 className={styles.title}>
            Proof of <a>Humanity</a>
          </h2>
        </Box>
        <Box sx={{display:{ xs: 'flex', md: 'none' }}}>
          <h3 className={styles.titleSmall}>
            Proof of <a>Humanity</a>
          </h3>
        </Box>
        <p className={styles.description}>
          Get started by joining our next event{' '}
        </p>

        <div className={styles.numberlist}>
              <div className={styles.previousUserText}>
                If you have successfully participated in a previous event, then use your existing <Link href="/id-list"> ΣID address</Link> and skip step 1.
              </div>
          <h3>Create ID</h3>
            <div className ={styles.listItems}>
              <ListItem sx={{ display: 'list-item' }}>
                If this is your first event, create a new <a href="https://docs.ergoplatform.com/dev/wallet/" target="_blank" rel="noopener noreferrer"> Ergo wallet</a>. This wallet should only be used for ErgoNation and will contain your anonymous ΣID. Do not reveal it to anyone.
              </ListItem>
              <ListItem sx={{ display: 'list-item' }}>
                Use <a href="https://github.com/ergoMixer/ergoMixBack/releases" target="_blank" rel="noopener noreferrer">ErgoMixer</a> to send a minimum of 1 ERG into it. The mixing process may take some time. Start it right away to be ready for the verification event.
              </ListItem>
              <ListItem sx={{ display: 'list-item' }}>
                All funds going in and out of the ΣID address must go through the mixer to preserve anonymity.            
              </ListItem>
            </div>
          <h3>Verify ID </h3>
            <div className ={styles.listItems}>
              <ListItem sx={{ display: 'list-item' }}>
                Join the next monthly ΣID verification event on July 11th 2022 at 13.00 UTC for instructions. The event itself will start 13.10 UTC, and end 13.30 UTC.
              </ListItem>
              <ListItem sx={{ display: 'list-item' }}>
                Participants will play a short game. If successful, they will be able to verify the ID on-chain.
              </ListItem>
            </div>
          <h3>Use ID </h3>
            <div className ={styles.listItems}>
              <ListItem sx={{ display: 'list-item' }}>
                Ergo projects can engage the ΣID holders in governance, testing, whitelist, rewards, tasks, etc.
              </ListItem>
              <ListItem sx={{ display: 'list-item' }}>
                The ΣIDs will gather reputation through actions in the ecosystem. We encourage projects to engage ΣIDs that actively support decentralization, anonymity and the spirit of Ergo. To learn more about Ergo&apos;s vision read the  <a href="https://ergoplatform.org/en/blog/2021-04-26-the-ergo-manifesto/" target="_blank" rel="noopener noreferrer"> Ergo Manifesto</a>.
              </ListItem>
            </div>
        </div>
      </main>
      <Footer/>
    </div>
  )
}
